// PergaminoTextos.cpp
//
// Textos de los pergaminos del juego
/////////////////////////////////////////////////////////////////////////////

#include "Pergamino.h"

using namespace Abadia;

/////////////////////////////////////////////////////////////////////////////
// pergamino de la presentación
/////////////////////////////////////////////////////////////////////////////

char * Pergamino::pergaminoInicio = 
	" Ya al final de mi\x0d"
	"vida de pecador, mien-\x0d"
	"tras espero el mo-\x0d"
	"mento de perderme en\x0d"
	"el abismo sin fondo de\x0d"
	"la divinidad desierta y\x0d"
	"silenciosa; en esta\x0d"
	"celda de mi querido\x0d"
	"monasterio de Melk,\x0d"
	"donde aun me retiene\x0d"
	"mi cuerpo pesado y\x0d"
	"enfermo, me dispongo\x0d"
	"a dejar constancia en\x0d"
	"este pergamino de los\x0d"
	"hechos asombrosos y\x0d"
	"terribles que me fue\x0d"
	"dado presenciar en mi\x0d"
	"juventud.\x0d\x0d"
	" El sewor me conce-\x0d"
	"de la gracia de dar\x0d"
	"fiel testimonio de los\x0d"
	"acontecimientos que se\x0d"
	"produjeron en la aba-\x0d"
	"dia cuyo nombre in-\x0d"
	"cluso conviene ahora\x0d"
	"cubrir con un piadoso\x0d"
	"mando de silencio; ha-\x0d"
	"cia finales de 1327,\x0d"
	"cuando mi padre deci-\x0d"
	"dio que acompawara a\x0d"
	"fray Guillermo de \x0d"
	"Occam, sabio francis-\x0d"
	"cano que estaba a\x0d"
	"punto de iniciar una\x0d"
	"mision en el desem-\x0d"
	"pewo de la cual to-\x0d"
	"caria muchas ciuda-\x0d"
	"des famosas y aba-\x0d"
	"dias antiquisimas. Asi\x0d"
	"fue como me conver-\x0d"
	"ti al mismo tiempo en\x0d"
	"su amanuense y dis-\x0d"
	"cipulo; y no tuve que\x0d"
	"arrepentirme, porque\x0d"
	"con el fui testigo de\x0d"
	"acontecimientos dignos\x0d"
	"de ser registrados,\x0d"
	"para memorioa de los\x0d"
	"que vengan despues.\x0d\x0d"
	" Asi, mientras con\x0d"
	"los dias iba conocien-\x0d"
	"do mejor a mi maes-\x0d"
	"tro, llegamos a las\x0d"
	"faldas del monte don-\x0d"
	"de se levantaba la\x0d"
	"abadia. Y ya es hora\x0d"
	"de que, como nosotros\x0d"
	"entonces, a ella se\x0d"
	"acerque mi relato, y\x0d"
	"ojala mi mano no\x0d"
	"tiemble cuando me\x0d"
	"dispongo a narrar lo\x0d"
	"que sucedio despues...\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"autor: \x0d"
	"    Paco Menendez\x0d\x0d"
	"graficos y caratula: \x0d"
	"    Juan Delcan\x0d\x0d"
	"reingenieria inversa: \x0d"
	"    Manuel Abadia\x0d\x0d"
	"version Linux: Luzbel\x1a";

/////////////////////////////////////////////////////////////////////////////
// pergamino del final del juego
/////////////////////////////////////////////////////////////////////////////

char * Pergamino::pergaminoFinal = 
	" Desfigurado por la\x0d"
	"angustia, por el aco-\x0d"
	"so del veneno que ya\x0d"
	"serpenteaba abundante\x0d"
	"por sus venas, el\x0d"
	"otrora venerable ros-\x0d"
	"tro del anciando se\x0d"
	"veia repulsivo y gro-\x0d"
	"tesco.\x0d"
	" Habriamos podido\x0d"
	"atraparlo con calma,\x0d"
	"pero nos precipitamos\x0d"
	"con vehemencia sobre\x0d"
	"el. Logro zafarse y\x0d"
	"apreto el libro contra\x0d"
	"su pecho para defen-\x0d"
	"derlo. Yo lo tenia co-\x0d"
	"gido con la mano iz-\x0d"
	"quierda, mientras con\x0d"
	"la derecha trataba de\x0d"
	"mantener en alto la\x0d"
	"lampara. Pero roce\x0d"
	"su rostro con la lla-\x0d"
	"ma y emitio un so-\x0d"
	"nido ahogado, casi un\x0d"
	"rugido, dejando caer\x0d"
	"trozos de folio por\x0d"
	"la boca. Su mano\x0d"
	"derecha solto el li-\x0d"
	"bro, busco la lampa-\x0d"
	"ra y, de un golpe, me\x0d"
	"la arranco lanzandola\x0d"
	"hacia adelante...\x0d"
	" Se derramo el acei-\x0d"
	"te y en seguida el\x0d"
	"fuego prendio en el\x0d"
	"pergamino que ardio\x0d"
	"como un haz de hor-\x0d"
	"nija reseca. Todo su-\x0d"
	"cedio en pocos instan-\x0d"
	"tes; una llamarada se\x0d"
	"elevo desde los libros,\x0d"
	"como si aquellas pa-\x0d"
	"ginas milenarias lle-\x0d"
	"varan siglos esperan-\x0d"
	"do quemarse y goza-\x0d"
	"ran al satisfacer de\x0d"
	"pronto una sed inme-\x0d"
	"morial de ecpirosis.\x0d"
	" La abadia ardio du-\x0d"
	"rante tres dias y tres\x0d"
	"noches y de nada va-\x0d"
	"lieron los ultimos es-\x0d"
	"fuerzos.  Al tercer\x0d"
	"dia, curados los heri-\x0d"
	"dos, enterrados los\x0d"
	"cadaveres que habian\x0d"
	"quedado fuera de los\x0d"
	"edificios, los monjes\x0d"
	"y el resto de los po-\x0d"
	"bladores de la abadia\x0d"
	"recogieron sus perte-\x0d"
	"nencias y abandonaron\x0d"
	"la meseta, que aun\x0d"
	"humeaba, como un lu-\x0d"
	"gar maldito.\x0d"
	" Guillermo y yo nos\x0d"
	"alejamos de aquel pa-\x0d"
	"raje en dos cabalga-\x0d"
	"duras que encontramos\x0d"
	"por el bosque. Cuando\x0d"
	"llegamos a  Munich\x0d"
	"tuve que separarme,\x0d"
	"no sin derramar\x0d"
	"abundantes lagrimas,\x0d"
	"de mi buen maestro.\x0d"
	"Despues de darme\x0d"
	"muchos buenos con-\x0d"
	"sejos para mis fu-\x0d"
	"turos estudios, me\x0d"
	"estrecho entre sus\x0d"
	"brazos, con la ter-\x0d"
	"nura de un padre, y\x0d"
	"me dijo adios. Jamas\x0d"
	"volvi a verlo.\x0d"
	" Ahora, ya en el um-\x0d"
	"bral de la muerte,\x0d"
	"cuanto mas releo la\x0d"
	"historia que de ello ha\x0d"
	"resultado, menos se\x0d"
	"si esta contiene o no\x0d"
	"una trama distinguible\x0d"
	"de la mera sucesion\x0d"
	"natural de los aconte-\x0d"
	"cimientos y de los\x0d"
	"momentos que los re-\x0d"
	"lacionan entre si. Y\x0d"
	"es duro para este\x0d"
	"viejo monje no saber\x0d"
	"si la letra que ha es-\x0d"
	"crito contiene o no\x0d"
	"algun sentido oculto,\x0d"
	"ni si contiene mas de\x0d"
	"uno, o muchos, o nin-\x0d"
	"guno. Pero quizas esta\x0d"
	"incapacidad sea pro-\x0d"
	"ducto de la sombra\x0d"
	"que la gran tiniebla\x0d"
	"que se aproxima, pro-\x0d"
	"yecta sobre este\x0d"
	"mundo ya viejo.\x0d"
	" Hace frio en el\x0d"
	"scriptorium, me duele\x0d"
	"el pulgar. Dejo este\x0d"
	"texto, no se para\x0d"
	"quien, este texto, que\x0d"
	"ya no se de que ha-\x0d"
	"bla.\x0d\x1a";
